### ISSUE TITLE
**ORACLE** - это не **MS SQL Server**

### ISSUE THREAD

**Issue by jvxram** [tsv19su254052/LoadWorkDataAirFlightsDBNew#54]
**ORACLE** - это не **MS SQL Server**
Я время от времени делал подходы с целью изучить его получше и понял, что им нужно заниматься всерьез.
Там документация платная. Что-то скачать с сайта - нужна учетка с действующим договором.
Это нужен отдельный человек (хороший грамотный специалист с большой зарплатой), который будет заниматься только им - администрировать его, ездить на симпозиумы, на обучение, на дообучение, на переобучение в Москву, сдавать там экзамены, получать их дипломы и сертификаты. Такое даже SIEMENS-у в некоторых отраслях не по силам.

На мой взгляд - если Вы не в Москве и денег мало, то это просто не реально.

В Москве с фирме-интеграторе, которая в 2014-м продавала транспортный процессинг из коробки, есть человек, который делает на ORACLE под Linux. Но он там один.

А мы уже будем писать запросы к СУБД и обеспечивать прикладной уровень

_Originally posted by @tsv19su in https://github.com/tsv19su254052/LoadWorkDataAirFlightsDBNew/issues/1#issuecomment-1159575925_

**Comment by jvxram** [comment]
поэтому MS SQL Server - это такая золотая середина, на которой сидят все

**Comment by tsv19su** [comment]
Дистрибутивы и графические оболочки есть на сервере
```
Q:\Oracle\Oracle SQL Developer\Oracle SQL Developer 21.4.3 
Q:\Oracle\Oracle Database 21c (Linux x86-64б HPUX IA64 и Windows) 2021 12.3\Windows 
```

можете посмотреть, попробовать, поизучать, если есть время и желание

**Comment by tsv19su254052** [comment]
я смотрел ORACLE, когда его под винду не было - только Солярис кажется
Солярис  - только в Москве тогда был

Полностью согласен

**Comment by tsv19su254052** [comment]
ну разве что только для кругозора, чтобы на обучении хотя бы понимать, о чем идет речь

**Comment by tsv19su254052** [comment]
Тема закрыта
