### ISSUE TITLE
по-моему, если ты не в Москве и мало денег - вообще все не реально

### ISSUE THREAD

**Issue by tsv19su** [tsv19su254052/LoadWorkDataAirFlightsDBNew#55]
по-моему, если ты не в Москве и мало денег - вообще все не реально
Посмотри на Авито и увидишь, что все, что сложнее и дороже штанов и кроссовок - 99 процентов продают в Москве
Нормальные зарплаты только там. 
Но там и 2-шка в старом клоповнике на шоссе Энтузиастов стоит 2 ... 3 ляма долларов.

Вся Россия работает за трудодни, а питается тем, что на огороде вырастет

_Originally posted by @jvxram in https://github.com/tsv19su254052/LoadWorkDataAirFlightsDBNew/issues/1#issuecomment-1159576619_

**Comment by tsv19su** [comment]
+++ плюсую

**Comment by tsv19su** [comment]
все ресурсы там

**Comment by tsv19su254052** [comment]
если Вы не в Москве, то скорее всего денег у Вас будет мало
и в Москве тоже денег много не у всех

**Comment by tsv19su254052** [comment]
закрываю тему
