### ISSUE TITLE
Считал лет 6 тому назад, сколько для юрлица будет инфраструктура на облаке

### ISSUE THREAD

**Issue by tsv19su** [tsv19su254052/LoadWorkDataAirFlightsDBNew#59]
Считал лет 6 тому назад, сколько для юрлица будет инфраструктура на облаке
10 Мбит в локалку, 20 Гбайт на диске, 500 Гбайт траффика ...
Итого 350 тыс. руб в месяц

Своя инфраструктура - по-любому выгоднее
С другой стороны: если из вычислительной техники только АйФон и только ты да я да мы с тобой и деньги есть, а чего-то хочется, тогда может и вариант ...

_Originally posted by @tsv19su254052 in https://github.com/tsv19su254052/LoadWorkDataAirFlightsDBNew/issues/1#issuecomment-1159581440_

**Comment by tsv19su** [comment]
если речь идет про PaaS, то у меня желания переезжать на командную строку с ключами и путями, как в фильме **Хакеры** или **Мистер Робот**, пока нету

сейчас снова мода на Linux пошла
видимо это из-за Docker-а

народ лезет в какие-то выси поперед всех, а потом выясняет, что уже опоздал или уже не надо, как было в 2019-м с дата саентистами

**Comment by tsv19su254052** [comment]
350 - это нашли самого дешевого по акции, а так было у всех в районе 500

Мне знакомые ВЭБ-разработчики говорят, что хостинг сайтов дешевый.
Но мне не сайт нужно поднять, а всю инфраструктуру

**Comment by tsv19su254052** [comment]
Вообще нет задачи все дергать с сайтов, причесывать данные и делать что-то само по себе в чисто локальном виде. Этот проект взаимодействует с другими справочными сайтами на API-шках и дает взаимодействовать с собой другим проектам

**Comment by tsv19su254052** [comment]
Закрываю это обсуждение
