### ISSUE TITLE
Зачем нам теперь отдельные базы по авиакомпаниям, объектам и маршрутам?

### ISSUE THREAD

**Issue by tsv19su254052** [tsv19su254052/LoadWorkDataAirFlightsDBNew#71]
А какая практическая польза держать и обслуживать:
 - отдельную базу по авиакомпаниям,
 - отдельную базу по объектам и маршрутам, если переходим от **тестовых баз** к **тестовым таблицам**? Если из внешних проектов будут лазить в авиакомпании, то пускай лезут в общую базу

_Originally posted by @tsv19su254052 in https://github.com/tsv19su254052/LoadWorkDataAirFlightsDBNew/issues/1#issuecomment-1166244656_

**Comment by tsv19su254052** [comment]
Теперь надо скопировать таблицы из отдельной базы авиакомпаний и в таблицы в общей базе со всеми делами

https://github.com/tsv19su254052/LoadWorkDataAirFlightsDBNew/issues/61#issuecomment-1163467441

**Comment by tsv19su** [comment]
На это было несколько причин:
 - для экономии места, так как общая рабочая и общая тестовая базы использовали эти отдельные базы,
 - версии 6, 7 , 8 используют эти 2 отдельные базы,
 - при загрузке данных в них нет справочников,
 - справочники дополняются без внесения изменений в общие базы всех версий,
 - чтобы при аппаратных сбоях не терять накопленные справочники..

Если перенесем эти 2 отдельные базы в общую, то придется в каждой версии 6, 7, 8 и так далее заполнять эти справочники

**Comment by tsv19su254052** [comment]
Теперь понятно
